/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MaliciousAirdrop__factory } from "./MaliciousAirdrop__factory";
export { MockUSDT__factory } from "./MockUSDT__factory";
